export const NEXT_PUBLIC_API_URL = process.env.NEXT_PUBLIC_API_URL;
export const NEXT_PUBLIC_FIREBASE_CONFIG =
  process.env.NEXT_PUBLIC_FIREBASE_CONFIG;
export const NEXT_PUBLIC_SYNCFUSION_KEY =
  process.env.NEXT_PUBLIC_SYNCFUSION_KEY;
