import type { Metadata, Viewport } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';
import AppProvider from '../components/appProvider';
import SessionWrapper from './SessionWrapper';
import Favicon from '@/components/favIcon';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  manifest: '/manifest.json',
  title: 'Connect',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  themeColor: '#FFFFFF',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <head>
        <Favicon />
        <link rel='manifest' href='/manifest.json' />
        <link
          rel='icon'
          type='image/png'
          sizes='192x192'
          href='/icon-192x192.png'
        />
        <link
          rel='icon'
          type='image/png'
          sizes='512x512'
          href='/icon-512x512.png'
        />
        <meta name='theme-color' content='#000000' />
      </head>
      <body className={inter.className}>
        <SessionWrapper>
          <AppProvider>{children}</AppProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
